global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /prometheus/metrics
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'grafana'
    scheme: http
    metrics_path: /grafana/metrics
    static_configs:
      - targets: ['grafana:3000']
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
