name: Bug report
description: Report a reproducible problem
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and expected behavior
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction
      description: Exact steps/commands (include `make ci` output if relevant)
      render: bash
  - type: input
    id: env
    attributes:
      label: Environment
      description: OS/Runner and versions (Docker, Caddy, Prometheus)
