name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      LE_EMAIL: ${{ secrets.LE_EMAIL || 'admin@example.com' }}
      DOMAIN: snapdiscounts.nl
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml jsonschema yamllint

      - name: Docker info
        run: docker info

      - name: Validate infra (Caddy + Prometheus)
        run: bash scripts/validate_infra.sh

      - name: Lint terms (non-blocking)
        run: bash scripts/lint_terms.sh || true

      - name: Validate JSON event samples
        run: python scripts/validate_events.py
