name: Test self-hosted runner

on:
  workflow_dispatch:  # handmatig starten via GitHub
  push:
    branches: [ main ]

jobs:
  test-runner:
    runs-on: [self-hosted, linux, x64, vps, prod]
    steps:
      - name: Test opdracht
        run: |
          echo "✅ De runner werkt op $(hostname)"
          date
          uptime
