name: CI
on:
  push:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      DOMAIN: ${{ secrets.DOMAIN || 'snapdiscounts.nl' }}
      LE_EMAIL: ${{ secrets.LE_EMAIL || 'r.davelaar@icloud.com' }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Validate infra
        run: |
          bash scripts/validate_infra.sh
      - name: Lint terms (non-blocking)
        run: |
          bash scripts/lint_terms.sh || true
      - name: Validate event samples
        run: |
          python3 scripts/validate_events.py
